### ISSUE TITLE
RuntimeError: memory access out of bounds when Removing and Destroying bodies

### ISSUE THREAD

**Issue by bobbydigitales** [jrouwe/JoltPhysics.js#11]
I'm trying to add and remove bodies to the simulation in my project, but when I call `RemoveBody()` and `DestroyBody()` I get a memory access out of bounds error.

I modified the falling_shapes demo so that it repeatedly creates, then removes and destroys bodies, and it does the same thing: https://gist.github.com/bobbydigitales/d385067b541a951619223da889129acf

You should be able to just drop this in and repro immediately:

Uncaught (in promise) RuntimeError: memory access out of bounds
    at JPH::Body::IsActive() JPH::Body::IsActive() const (Body.h:47)
    at JPH::BodyManager::DestroyBodies(JPH::BodyID const*, JPH::BodyManager::RemoveBodyInternal(JPH::BodyID const&) (BodyManager.cpp:305)
    at JPH::BodyManager::DestroyBodies(JPH::BodyID const*, JPH::BodyManager::DestroyBodies(JPH::BodyID const*, int) (BodyManager.cpp:379)
    at JPH::BodyInterface::DestroyBody(JPH::BodyID JPH::BodyInterface::DestroyBody(JPH::BodyID const&) (BodyInterface.cpp:75)
    at emscripten_bind_BodyInterface_DestroyBody_1 (0916889e:0x47aea)
    at jolt-physics.wasm-compat.js:783:22
    at BodyInterface.DestroyBody.BodyInterface.DestroyBody (jolt-physics.wasm-compat.js:8232:3)
    at falling_shapes.html:160:27

What is the correct way to add and remove bodies from the simulation in the WASM version? Are there any other things to be wary of in terms of memory being allocated but not deallocated?

**Comment by jrouwe** [comment]
It should be:

```
bodyInterface.RemoveBody(body.GetID())
bodyInterface.DestroyBody(body.GetID())
```

It looks like you're passing the body instead of the ID.

**Comment by bobbydigitales** [comment]
Doh! Thanks and sorry for wasting your time!
